# Generated by Django 5.2.7 on 2025-10-07 02:40

import catalogodigital.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('administrador', models.ForeignKey(limit_choices_to={'rol': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='catalogos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catálogo',
                'verbose_name_plural': 'Catálogos',
                'ordering': ['categoria__codigo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('numero_orden', models.PositiveIntegerField(help_text='Orden del capítulo dentro del catálogo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('administrador', models.ForeignKey(limit_choices_to={'rol': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='capitulos_creados', to=settings.AUTH_USER_MODEL)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='catalogodigital.catalogo')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'ordering': ['catalogo__categoria__codigo', 'catalogo__nombre', 'numero_orden'],
                'unique_together': {('catalogo', 'numero_orden')},
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la categoría', max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('administrador', models.ForeignKey(limit_choices_to={'rol': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['codigo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='catalogo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogos', to='catalogodigital.categoria'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REVISION', 'En revisión'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=10)),
                ('numero_orden', models.PositiveIntegerField(help_text='Orden del video dentro del capítulo')),
                ('archivo_video', models.FileField(help_text='Formatos permitidos: MP4, AVI, MOV, MKV, WEBM', upload_to=catalogodigital.models.video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv', 'webm'])])),
                ('duracion', models.DurationField(blank=True, help_text='Duración del video en formato HH:MM:SS', null=True)),
                ('tamaño_archivo', models.BigIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('resolucion', models.CharField(blank=True, help_text='Ej: 1920x1080', max_length=20, null=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Imagen de vista previa del video', null=True, upload_to='thumbnails/')),
                ('visualizaciones', models.PositiveIntegerField(default=0)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('administrador', models.ForeignKey(limit_choices_to={'rol': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='videos_subidos', to=settings.AUTH_USER_MODEL)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='catalogodigital.capitulo')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['capitulo__catalogo__categoria__codigo', 'capitulo__catalogo__nombre', 'capitulo__numero_orden', 'numero_orden'],
                'unique_together': {('capitulo', 'numero_orden')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='catalogo',
            unique_together={('categoria', 'nombre')},
        ),
        migrations.CreateModel(
            name='VisualizacionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visualizacion', models.DateTimeField(auto_now_add=True)),
                ('progreso', models.FloatField(default=0.0, help_text='Progreso de visualización en porcentaje (0-100)')),
                ('completado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_vistos', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizaciones_usuario', to='catalogodigital.video')),
            ],
            options={
                'verbose_name': 'Visualización de Video',
                'verbose_name_plural': 'Visualizaciones de Videos',
                'ordering': ['-fecha_visualizacion'],
                'unique_together': {('video', 'usuario')},
            },
        ),
    ]
