# Generated by Django 5.2.7 on 2025-10-07 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogodigital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Contenido del comentario', max_length=1000)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('comentario_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='catalogodigital.comentariovideo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_videos', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='catalogodigital.video')),
            ],
            options={
                'verbose_name': 'Comentario de Video',
                'verbose_name_plural': 'Comentarios de Videos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CompartirVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LINK', 'Enlace copiado'), ('SOCIAL', 'Red social'), ('EMAIL', 'Correo electrónico'), ('WHATSAPP', 'WhatsApp'), ('OTROS', 'Otros')], default='LINK', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos_compartidos', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartidas', to='catalogodigital.video')),
            ],
            options={
                'verbose_name': 'Video Compartido',
                'verbose_name_plural': 'Videos Compartidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LikeComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_comentario', to='catalogodigital.comentariovideo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like de Comentario',
                'verbose_name_plural': 'Likes de Comentarios',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('comentario', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='LikeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_liked', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='catalogodigital.video')),
            ],
            options={
                'verbose_name': 'Like de Video',
                'verbose_name_plural': 'Likes de Videos',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('video', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='VideoGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_guardados', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardados', to='catalogodigital.video')),
            ],
            options={
                'verbose_name': 'Video Guardado',
                'verbose_name_plural': 'Videos Guardados',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('video', 'usuario')},
            },
        ),
    ]
