# Generated by Django 5.2.7 on 2025-10-11 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogodigital', '0002_comentariovideo_compartirvideo_likecomentario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos_subidos_por', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='administrador',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_aprobados_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
