# Generated by Django 5.2.7 on 2025-10-14 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogodigital', '0003_video_autor_alter_video_administrador'),
    ]

    operations = [
        # 1) Primero crear los FKs nuevos
        migrations.AddField(
            model_name='capitulo',
            name='categoria',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='capitulos',
                to='catalogodigital.categoria'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='catalogo',
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='categorias',
                to='catalogodigital.catalogo'
            ),
            preserve_default=False,
        ),

        # 2) (Opcional) Ajustes de campos
        migrations.AlterField(
            model_name='capitulo',
            name='numero_orden',
            field=models.PositiveIntegerField(help_text='Orden del capítulo dentro de la categoría'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(help_text='Código único dentro del catálogo', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),

        # 3) Constraints que dependen de los FKs ya creados
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('catalogo', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='capitulo',
            unique_together={('categoria', 'numero_orden')},
        ),
        migrations.AlterUniqueTogether(
            name='catalogo',
            unique_together=set(),
        ),

        # 4) Quitar los campos viejos (ya no se usan)
        migrations.RemoveField(
            model_name='catalogo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='capitulo',
            name='catalogo',
        ),

        # 5) Por último, los ModelOptions (ordering/verbose_name) que referencian relaciones nuevas
        migrations.AlterModelOptions(
            name='catalogo',
            options={'ordering': ['nombre'], 'verbose_name': 'Catálogo', 'verbose_name_plural': 'Catálogos'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['catalogo__nombre', 'codigo', 'nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='capitulo',
            options={'ordering': ['categoria__catalogo__nombre', 'categoria__codigo', 'numero_orden'], 'verbose_name': 'Capítulo', 'verbose_name_plural': 'Capítulos'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['capitulo__categoria__catalogo__nombre', 'capitulo__categoria__codigo', 'capitulo__numero_orden', 'numero_orden'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
