# Generated by Django 5.2.7 on 2025-10-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogodigital', '0004_alter_capitulo_options_alter_catalogo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitulo',
            options={'ordering': ['categoria__catalogo__nombre', 'categoria__codigo', 'nombre'], 'verbose_name': 'Capítulo', 'verbose_name_plural': 'Capítulos'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['capitulo__categoria__catalogo__nombre', 'capitulo__categoria__codigo', 'capitulo__nombre', 'titulo'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterUniqueTogether(
            name='capitulo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='capitulo',
            name='numero_orden',
        ),
        migrations.RemoveField(
            model_name='video',
            name='numero_orden',
        ),
    ]
