# Generated by Django 5.2.7 on 2025-12-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogodigital', '0005_alter_capitulo_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='tipo',
            field=models.CharField(choices=[('FISICO', 'Físico'), ('DIGITAL', 'Digital')], default='DIGITAL', max_length=10),
        ),
    ]
