# Generated by Django 5.2.7 on 2025-10-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='codigo_usuario',
        ),
    ]
