# Generated by Django 5.2.7 on 2025-12-09 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_user_codigo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_email', models.BooleanField(default=True, verbose_name='Notificaciones por email')),
                ('notif_push', models.BooleanField(default=False, verbose_name='Notificaciones push')),
                ('notif_nuevos_videos', models.BooleanField(default=True, verbose_name='Notificar nuevos videos')),
                ('notif_comentarios', models.BooleanField(default=True, verbose_name='Notificar comentarios')),
                ('perfil_visible', models.BooleanField(default=True, verbose_name='Perfil público')),
                ('mostrar_email', models.BooleanField(default=False, verbose_name='Mostrar email')),
                ('mostrar_actividad', models.BooleanField(default=True, verbose_name='Mostrar actividad')),
                ('autoplay', models.BooleanField(default=False, verbose_name='Reproducción automática')),
                ('calidad_video', models.CharField(choices=[('auto', 'Automática'), ('1080p', '1080p (HD)'), ('720p', '720p'), ('480p', '480p'), ('360p', '360p')], default='auto', max_length=10, verbose_name='Calidad de video')),
                ('subtitulos_auto', models.BooleanField(default=False, verbose_name='Subtítulos automáticos')),
                ('tema', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('auto', 'Automático')], default='light', max_length=10, verbose_name='Tema')),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('pt', 'Português')], default='es', max_length=5, verbose_name='Idioma')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Usuario',
                'verbose_name_plural': 'Preferencias de Usuarios',
            },
        ),
    ]
